name: "Install SQLite"
description: "Downloads SQLite directly from https://sqlite.org"

runs:
  using: "composite"
  steps:
    - name: Install SQLite
      env:
        SQLITE_VERSION: "3490100"
        YEAR: 2025
      run: |
        curl -o /tmp/sqlite.zip https://sqlite.org/$YEAR/sqlite-tools-linux-x64-$SQLITE_VERSION.zip > /dev/null
        echo "y" | unzip -j /tmp/sqlite.zip sqlite3 -d /usr/local/bin/
        sqlite3 --version
      shell: bash
