# Copyright 2023-2025 the Limbo authors. All rights reserved. MIT license.

[workspace]
resolver = "2"
members = [
    "bindings/go",
    "bindings/java",
    "bindings/javascript",
    "bindings/python",
    "bindings/rust",
    "bindings/wasm",
    "cli",
    "core", 
    "extensions/completion",
    "extensions/core",
    "extensions/crypto",
    "extensions/csv",
    "extensions/percentile",
    "extensions/regexp",
    "extensions/series",
    "extensions/tests",
    "extensions/time",
    "extensions/uuid",
    "macros",
    "simulator",
    "sqlite3",
    "stress",
    "tests",
    "vendored/sqlite3-parser/sqlparser_bench",
]
exclude = ["perf/latency/limbo"]

[workspace.package]
version = "0.0.22-pre.1"
authors = ["the Limbo authors"]
edition = "2021"
license = "MIT"
repository = "https://github.com/tursodatabase/limbo"

[workspace.dependencies]
limbo_completion = { path = "extensions/completion", version = "0.0.22-pre.1" }
limbo_core = { path = "core", version = "0.0.22-pre.1" }
limbo_crypto = { path = "extensions/crypto", version = "0.0.22-pre.1" }
limbo_csv = { path = "extensions/csv", version = "0.0.22-pre.1" }
limbo_ext = { path = "extensions/core", version = "0.0.22-pre.1" }
limbo_ext_tests = { path = "extensions/tests", version = "0.0.22-pre.1" }
limbo_ipaddr = { path = "extensions/ipaddr", version = "0.0.22-pre.1" }
limbo_macros = { path = "macros", version = "0.0.22-pre.1" }
limbo_percentile = { path = "extensions/percentile", version = "0.0.22-pre.1" }
limbo_regexp = { path = "extensions/regexp", version = "0.0.22-pre.1" }
limbo_series = { path = "extensions/series", version = "0.0.22-pre.1" }
limbo_sqlite3_parser = { path = "vendored/sqlite3-parser", version = "0.0.22-pre.1" }
limbo_time = { path = "extensions/time", version = "0.0.22-pre.1" }
limbo_uuid = { path = "extensions/uuid", version = "0.0.22-pre.1" }
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"

[profile.release]
debug = "line-tables-only"
codegen-units = 1
panic = "abort"
lto = true

[profile.antithesis]
inherits = "release"
debug = true
codegen-units = 1
panic = "abort"
lto = true

[profile.bench-profile]
inherits = "release"
debug = true

[profile.dist]
inherits = "release"
lto = "thin"
