[package]
name = "ruby-limbo"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
rutie = "0.8.0"
limbo_core = { path = "../../core", features = ["io_uring"] }
