[project]
dependencies = [
    "antithesis>=0.1.17",
    "pyturso"
]
description = "Add your description here"
name = "antithesis-tests"
requires-python = ">=3.13"
version = "0.1.0"

[tool.uv.sources]
pyturso = { workspace = true }
