[package]
name = "limbo_ext"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true


[features]
default = []
static = []

[dependencies]
limbo_macros = { path = "../../macros" }
