name: Update PR Description

on:
  pull_request:
    types: 
      - opened
      - edited
  pull_request_review:
    types:
      - submitted
      - dismissed

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update PR Description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          AUTHOR_USERNAME: ${{ github.event.pull_request.user.login }}
        run: |
          # Get author's full name
          AUTHOR_FULL_NAME=$(gh api "users/${AUTHOR_USERNAME}" | jq -r '.name // "'"${AUTHOR_USERNAME}"'"')
          
          # Prepare author line
          AUTHOR_LINE="Author: ${AUTHOR_FULL_NAME} (@${AUTHOR_USERNAME})"
          
          # Find reviewers
          REVIEWERS=$(gh pr view $PR_NUMBER --json reviewRequests --jq '.reviewRequests[].login // empty')
          
          # If no reviewers from review requests, try to get reviewers from completed reviews
          if [ -z "$REVIEWERS" ]; then
            REVIEWERS=$(gh pr view $PR_NUMBER --json reviews --jq '.reviews[] | select(.state == "APPROVED") | .author.login' | head -n 1)
          fi
          
          # Prepare reviewers line
          REVIEWERS_LINE=""
          if [ -n "$REVIEWERS" ]; then
            REVIEWER_DETAILS=()
            for reviewer in $REVIEWERS; do
              # Get reviewer's full name
              REVIEWER_FULL_NAME=$(gh api "users/${reviewer}" | jq -r '.name // "'"${reviewer}"'"')
              REVIEWER_DETAILS+=("${REVIEWER_FULL_NAME} (@${reviewer})")
            done
            REVIEWERS_LINE="Reviewed-by: $(IFS=, ; echo "${REVIEWER_DETAILS[*]}")"
          fi
          
          # Fetch current PR description
          CURRENT_DESC=$(gh pr view $PR_NUMBER --json body --jq .body)
          
          # Remove existing Author and Reviewed-by lines
          UPDATED_DESC=$(echo "$CURRENT_DESC" | sed -E '/^(Author:|Reviewed-by:)/d')
          
          # Combine description
          UPDATED_DESC="${UPDATED_DESC}
${AUTHOR_LINE}"
          
          # Add Reviewed-by line if reviewers exist
          if [ -n "$REVIEWERS_LINE" ]; then
            UPDATED_DESC="${UPDATED_DESC}
${REVIEWERS_LINE}"
          fi
          
          # Update the PR description
          echo "$UPDATED_DESC" | gh pr edit $PR_NUMBER --body-file -

      - name: Check for Errors
        if: failure()
        run: |
          echo "Failed to update PR description"
          exit 1